### PR TITLE
Fixes citation to use full document.domain sans www; Fixes #33

### LINKED ISSUE #33: attribution is undefined
use a reasonable default for the attribution

### PR DESCRIPTION
**Pull request by scott2b**
**What?**
Fix citation to be the document.domain w/out any prefixing www.

**Why?**
citation implementation was not returning any value. Opted against previous approach of slicing the domain. I'd like to see examples of what an undesirable long domain looks like before doctoring it

**Reviewers**
@rapoulson

### CODE REVIEW

File: src/js/bookmarklet.js [hunk 1]
```diff
@@ -48,8 +48,10 @@ function iFrame(apiRoot) {
     }
 
     function grabCitation(){
-      var cite;
-      document.domain.split("\.")[0];
+      var cite = document.domain;
+      if (cite.indexOf('www.') == 0) {
+          cite = cite.slice(4);
+      }
```
Comment (rapoulson) [inline src/js/bookmarklet.js:54]: Nice, I didn't know about indexOf. I think we're still going to run into the problem we currently have on prod where document.domain returns "pullquote.knightlab.com", though.

Comment (scott2b) [reply src/js/bookmarklet.js:54]: Ok. I can't really be sure about that until i deploy. I am going to merge and stage this to see. If it is pulling the wrong domain I'll open a new ticket.

Also, I am going to change `==` to `===` which I should have here

Comment (rapoulson) [reply src/js/bookmarklet.js:54]: merge on :shipit:
